# Generated by Django 4.2.2 on 2023-06-22 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("engine_size", models.IntegerField()),
                ("mileage", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        choices=[("4wd", "4 Wheel Drive"), ("2wd", "2 Wheel Drive")],
                        max_length=255,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        max_length=255,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("suv", "SUV"),
                            ("saloon", "Saloon"),
                            ("hatchback", "Hatchback"),
                            ("pickup", "Pickup"),
                            ("btv", "Buses, Taxis and Vans"),
                            ("station wagon", "Station Wagon"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("foreign used", "Foreign Used"),
                            ("locally used", "Locally Used"),
                        ],
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="cars")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cars.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="cars", to="cars.carfeature"
            ),
        ),
    ]
